import dotenv from "dotenv";
dotenv.config();

const DATABASE_URL = process.env.DATABASE_URL;

const CLIENT_URL = process.env.CLIENT_URL;

const JWT_SECRET = process.env.JWT_SECRET;
const JWT_EXPIRATION_TIME = process.env.JWT_EXPIRATION_TIME;
const REFRESH_SECRET = process.env.REFRESH_SECRET;
const REFRESH_EXPIRATION_TIME = process.env.REFRESH_EXPIRATION_TIME;

const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;

const EMAIL_USER = process.env.EMAIL_USER;
const EMAIL_PASS = process.env.EMAIL_PASS;

const NODE_ENV = process.env.NODE_ENV;

const CLERK_PUBLISHABLE_KEY = process.env.CLERK_PUBLISHABLE_KEY;
const CLERK_SECRET_KEY = process.env.CLERK_SECRET_KEY;

const CLIENT_SCREE_JWT = process.env.CLIENT_SCREE_JWT;

const SECRET = process.env.SECRET;

const PORT = process.env.PORT;

const GOOGLE_AUTH_ID = process.env.GOOGLE_AUTH_ID;
const GOOGLE_AUTH_SECRET = process.env.GOOGLE_AUTH_SECRET;
const GOOGLE_AUTH_SERVER_CALLBACK = process.env.GOOGLE_AUTH_SERVER_CALLBACK;
const GOOGLE_AUTH_URL_SUCCESS = process.env.GOOGLE_AUTH_URL_SUCCESS;

const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY;

const STRIPE_PUBLISHABLE_KEY = process.env.STRIPE_PUBLISHABLE_KEY;

export {
  DATABASE_URL,
  STRIPE_SECRET_KEY,
  JWT_SECRET,
  JWT_EXPIRATION_TIME,
  REFRESH_SECRET,
  REFRESH_EXPIRATION_TIME,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  EMAIL_USER,
  EMAIL_PASS,
  CLIENT_URL,
  CLERK_PUBLISHABLE_KEY,
  CLERK_SECRET_KEY,
  NODE_ENV,
  PORT,
  CLIENT_SCREE_JWT,
  SECRET,
  GOOGLE_AUTH_ID,
  GOOGLE_AUTH_SECRET,
  GOOGLE_AUTH_SERVER_CALLBACK,
  GOOGLE_AUTH_URL_SUCCESS,
  STRIPE_PUBLISHABLE_KEY,
};
